### PR TITLE
Add ARM support

### PR DESCRIPTION
**Pull request by kenshin54**
Since the MacBook with Apple M1 chip becomes more popular, this PR added the ARM support. I don't see any CI configuration in this project, just follow the existing setup, pushed all the dependencies. This increased the repo quite a lot, now it's very close to the Go mod limitation (500MB). If there is a better way, please let me know.

### CODE REVIEW

**Comment by kai-zhong** [comment]
can this PR be merged? i'm using Apple M1 as dev environment. i have tested, it works.

**Comment by dvaldivia** [comment]
@kenshin54 why did you close this PR?

**Comment by dumim** [comment]
Yep, why was this closed? This cannot be complied for ARM at the moment.

**Comment by dumim** [comment]
For anyone ending up here - @kenshin54 's [forked repo](https://github.com/kenshin54/lilliput) works perfectly on Apple Silicon: https://github.com/discord/lilliput/issues/95

**Pull request closed without merging**
